### ISSUE TITLE
Moving "excluded" when selected not to

### ISSUE THREAD

**Issue by ProjektPremium** [phpbb-extensions/autogroups#160] opened 2021-03-07 08:04 UTC
With the setting to exclude particular groups, every time it updates the groups, it adds my moderator accounts to the other member groups I have set up by membership date even though it states those groups were selected to be excluded.

**Comment by iMattPro** [comment] 2021-03-07 16:49
There is no setting to exclude members of groups. Every member who meets a condition will be added or removed to a group.

**Comment by ProjektPremium** [comment] 2021-03-07 22:37
Is there a way you can set it so it doesn't select other groups? I'm in the Admin group on my site and I've set it to put members in groups based on their membership time and it keeps putting me in that group as well as the Admin group but not setting me as default.

Then because I have set it to 2 minutes between replies, and I've been added to the other group, I have to wait to reply myself and keep removing myself from that group because every time I log in, I'm back in that group again.

**Comment by iMattPro** [comment] 2021-03-08 17:19
duplicate of #49

**Closed by iMattPro** 2021-03-08 17:19 UTC

**Comment by ProjektPremium** [comment] 2021-03-08 20:25
I think the solution would be just to exclude selected groups like admins, mods, global mods, staff etc.

Thanks for your response.
